---
driver_plugin: vagrant

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true

suites:
- name: default
  run_list:
  - recipe[etc_environment]
  attributes:
    etc_environment:
      DB_HOST: localhost
      DB_PORT: 3306
      SOME_JSON:
        a: 1
        b: "2"
        c:
          d: three
